In [38]:
from bs4 import BeautifulSoup  # For HTML parsing
import datetime
from tinydb import TinyDB, Query
import urllib3   # Website connections
import xlsxwriter
import requests
import pandas as pd  # For converting results to a dataframe and bar chart plots
import time
import lxml
import re

In [3]:
url = 'https://au.indeed.com/jobs?q=data+analyst&l=Sydney+NSW'
job = requests.get(url)

soup = BeautifulSoup(job.content, 'lxml')

### Scrape Data Analyst Job listing

 #### Create Empty Dataframe

In [4]:
max_results_per_city = 150
city_set = ["sydney+NSW","Ultimo+NSW","sydney+Western+Suburbs","Darlinghurst+NSW","Barangaroo+NSW",
            "Mascot+NSW","Parramatta+NSW","Surry+Hills+NSW","Macquarie+Park+NSW",
            "sydney+Inner+Suburbs+NSW","Hills+District+NSW","sydney+Central+Business+District+NSW",
            'New+South+Wales', 'Melbourne+VIC']
columns = ['city', 'job_title', 'company_name', 'location', 'summary', 'salary']
dsjob_df = pd.DataFrame(columns = columns)

In [5]:
a=[1,2,3,4,5,6]
a[0]=5
job_coll={}

In [21]:

for city in city_set:
    for start in range(0, max_results_per_city,1000):
        page = requests.get('https://au.indeed.com/jobs?q=data+scientist%2C+data+analyst%2C+research+scientist%2C+business+intelligence%2C+data+engineering&l=Sydney+NSW' + '&start=' + str(start))
        time.sleep(1)
        for div in soup.findAll(name='div', attrs={'class':'row'}):
            # specify row num for index of job posting in dataframe
            num = (len(job_coll) + 1)
            
            # Create an empty list to hold data for each posting
            #job_post = ['None','None','None','None','None','None']
            job_post = ['city', 'job_title', 'company_name', 'location', 'summary', 'salary']
            # append city name
            job_post[0]=city
           
            # grab job title
            for a in div.findAll(name='a', attrs={'data-tn-element':'jobTitle'}):
                job_post[1]=a['title']
            
            # grap company name
            company = div.findAll(name='span', attrs={'class':'company'})
            if len(company) > 0:
                for b in company:
                    job_post[2]=(b.text.strip())
            else:
                sec_try = div.findAll(name='span', attrs= {'class': 'result-link-source'})
                for span in sec_try:
                    job_post[2]=(span.text)
                
            # grab location name
            c = div.findAll('span', attrs={'class':'location'})
            for span in c:
                job_post[3]=(span.text)
                    
            # grab summary text
            d = div.findAll('span', attrs={'class':'summary'})
            for span in d:
                job_post[4]=(span.text.strip())
                
            # grab salary
            e = div.findAll('span', attrs={'class':'no-wrap'})
            for span in e:
                job_post[5]=(span.text.strip())
                
            
            print ((job_post))
            
            job_coll[num]=job_post

['sydney+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['sydney+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['sydney+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['sydney+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['sydney+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['sydney+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['sydney+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['sydney+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['sydney+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['sydney+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['sydney+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['sydney+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['sydney+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['sydney+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['sydney+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['sydney+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['Ultimo+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Ultimo+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Ultimo+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Ultimo+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Ultimo+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Ultimo+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Ultimo+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Ultimo+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Ultimo+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Ultimo+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Ultimo+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Ultimo+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Ultimo+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Ultimo+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Ultimo+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Ultimo+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['sydney+Western+Suburbs', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['sydney+Western+Suburbs', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['sydney+Western+Suburbs', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['sydney+Western+Suburbs', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['sydney+Western+Suburbs', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['sydney+Western+Suburbs', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['sydney+Western+Suburbs', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['sydney+Western+Suburbs', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['sydney+Western+Suburbs', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['sydney+Western+Suburbs', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['sydney+Western+Suburbs', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['sydney+Western+Suburbs', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['sydney+Western+Suburbs', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['sydney+Western+Suburbs', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['sydney+Western+Suburbs', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['sydney+Western+Suburbs', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

['Darlinghurst+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Darlinghurst+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Darlinghurst+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Darlinghurst+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Darlinghurst+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Darlinghurst+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Darlinghurst+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Darlinghurst+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Darlinghurst+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Darlinghurst+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Darlinghurst+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Darlinghurst+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Darlinghurst+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Darlinghurst+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Darlinghurst+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Darlinghurst+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['Barangaroo+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Barangaroo+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Barangaroo+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Barangaroo+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Barangaroo+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Barangaroo+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Barangaroo+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Barangaroo+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Barangaroo+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Barangaroo+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Barangaroo+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Barangaroo+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Barangaroo+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Barangaroo+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Barangaroo+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Barangaroo+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

['Mascot+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Mascot+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Mascot+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Mascot+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Mascot+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Mascot+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Mascot+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Mascot+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Mascot+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Mascot+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Mascot+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Mascot+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Mascot+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Mascot+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Mascot+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Mascot+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['Parramatta+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Parramatta+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Parramatta+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Parramatta+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Parramatta+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Parramatta+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Parramatta+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Parramatta+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Parramatta+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Parramatta+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Parramatta+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Parramatta+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Parramatta+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Parramatta+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Parramatta+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Parramatta+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['Surry+Hills+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Surry+Hills+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Surry+Hills+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Surry+Hills+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Surry+Hills+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Surry+Hills+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Surry+Hills+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Surry+Hills+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Surry+Hills+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Surry+Hills+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Surry+Hills+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Surry+Hills+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Surry+Hills+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Surry+Hills+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Surry+Hills+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Surry+Hills+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

['Macquarie+Park+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Macquarie+Park+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Macquarie+Park+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Macquarie+Park+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Macquarie+Park+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Macquarie+Park+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Macquarie+Park+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Macquarie+Park+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Macquarie+Park+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Macquarie+Park+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Macquarie+Park+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Macquarie+Park+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Macquarie+Park+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Macquarie+Park+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Macquarie+Park+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Macquarie+Park+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['sydney+Inner+Suburbs+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['sydney+Inner+Suburbs+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['sydney+Inner+Suburbs+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['sydney+Inner+Suburbs+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['sydney+Inner+Suburbs+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

['Hills+District+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Hills+District+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Hills+District+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Hills+District+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Hills+District+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Hills+District+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Hills+District+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Hills+District+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Hills+District+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Hills+District+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Hills+District+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Hills+District+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Hills+District+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Hills+District+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Hills+District+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Hills+District+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['sydney+Central+Business+District+NSW', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['sydney+Central+Business+District+NSW', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['sydney+Central+Business+District+NSW', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['sydney+Central+Business+District+NSW', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['sydney+Central+Business+District+NSW', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['sydney+Central+Business+District+NSW', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['sydney+Central+Business+District+NSW', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['sydney+Central+Business+District+NSW', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['sydney+Central+Business+District+NSW', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['sydney+Central+Business+District+NSW', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['sydney+Central+Business+District+NSW', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

['New+South+Wales', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['New+South+Wales', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['New+South+Wales', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['New+South+Wales', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['New+South+Wales', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['New+South+Wales', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['New+South+Wales', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['New+South+Wales', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['New+South+Wales', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['New+South+Wales', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['New+South+Wales', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['New+South+Wales', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['New+South+Wales', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['New+South+Wales', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['New+South+Wales', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['New+South+Wales', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']
['Melbourne+VIC', 'Organisation & Methods Analyst', 'WEST 1 Australia', 'location', 'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...', '$55,000 - $65,000 a year']
['Melbourne+VIC', 'Data Analyst, Marketing Strategy & Insights', 'ANZ Banking Group', 'location', 'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....', 'salary']
['Melbourne+VIC', 'Data Scientist - Analytics', 'Domain Group', 'location', 'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...', 'salary']
['Melbourne+VIC', 'Data & Reporting Analyst (full-time or part-time opportunity)', 'AMP Ltd', 'location', "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...", 'salary']
['Melbourne+VIC', 'Data Analyst - Alexa', 'Amazon.com', 'Sydney NSW', 'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...', 'salary']
['Melbourne+VIC', 'Data Analyst', 'Department of Finance, Services & Innovation', 'Sydney NSW', 'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...', 'salary']
['Melbourne+VIC', 'Data Analyst', 'BT Financial Group', 'Sydney Central Business District NSW', 'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...', 'salary']
['Melbourne+VIC', 'Junior Data Scientist', 'The Eclair Group', 'Sydney NSW', 'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....', '$70,000 - $90,000 a year']
['Melbourne+VIC', 'Data Analyst', 'OpenAgent', 'Alexandria NSW', 'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...', 'salary']
['Melbourne+VIC', 'Data Migration Test analyst', 'Tata Consultancy Services (TCS)', 'Sydney NSW', 'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....', '$80,000 - $90,000 a year']
['Melbourne+VIC', 'Data Analyst', 'Datasii', 'Sydney NSW', 'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...', '$70,000 - $90,000 a year']
['Melbourne+VIC', 'Data Operations Analyst', 'Munich Re', 'Sydney NSW', 'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...', 'salary']
['Melbourne+VIC', 'Junior Data Scientist/ Machine Learning Engineer', 'Intellify', 'Sydney NSW', 'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...', '$80,000 - $100,000 a year']
['Melbourne+VIC', 'Data Analyst', 'World Fuel', 'Sydney NSW', 'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...', 'salary']
['Melbourne+VIC', 'Data Analyst', 'Robert Half Australia', 'location', 'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....', '$600 a week']
['Melbourne+VIC', 'Research & Insights Analyst', 'News Corp Australia', 'location', 'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....', 'salary']

In [22]:
len(job_coll)

448

In [23]:
job_coll

{1: ['sydney+NSW',
  'Organisation & Methods Analyst',
  'WEST 1 Australia',
  'location',
  'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...',
  '$55,000 - $65,000 a year'],
 2: ['sydney+NSW',
  'Data Analyst, Marketing Strategy & Insights',
  'ANZ Banking Group',
  'location',
  'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....',
  'salary'],
 3: ['sydney+NSW',
  'Data Scientist - Analytics',
  'Domain Group',
  'location',
  'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...',
  'salary'],
 4: ['sydney+NSW',
  'Data & Reporting Analyst (full-time or part-time opportunity)',
  'AMP Ltd',
  'location',
  "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...",
  'salary'],
 5: ['sydney+NSW',
  'Data Analyst - Alexa',
  'Amazon.com',
  'Sydney NSW',
  'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...',
  'salary'],
 6: ['sydney+NSW',
  'Data Analyst',
  'Department of Finance, Services & Innovation',
  'Sydney NSW',
  'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...',
  'salary'],
 7: ['sydney+NSW',
  'Data Analyst',
  'BT Financial Group',
  'Sydney Central Business District NSW',
  'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...',
  'salary'],
 8: ['sydney+NSW',
  'Junior Data Scientist',
  'The Eclair Group',
  'Sydney NSW',
  'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....',
  '$70,000 - $90,000 a year'],
 9: ['sydney+NSW',
  'Data Analyst',
  'OpenAgent',
  'Alexandria NSW',
  'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...',
  'salary'],
 10: ['sydney+NSW',
  'Data Migration Test analyst',
  'Tata Consultancy Services (TCS)',
  'Sydney NSW',
  'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....',
  '$80,000 - $90,000 a year'],
 11: ['sydney+NSW',
  'Data Analyst',
  'Datasii',
  'Sydney NSW',
  'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...',
  '$70,000 - $90,000 a year'],
 12: ['sydney+NSW',
  'Data Operations Analyst',
  'Munich Re',
  'Sydney NSW',
  'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...',
  'salary'],
 13: ['sydney+NSW',
  'Junior Data Scientist/ Machine Learning Engineer',
  'Intellify',
  'Sydney NSW',
  'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...',
  '$80,000 - $100,000 a year'],
 14: ['sydney+NSW',
  'Data Analyst',
  'World Fuel',
  'Sydney NSW',
  'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...',
  'salary'],
 15: ['sydney+NSW',
  'Data Analyst',
  'Robert Half Australia',
  'location',
  'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....',
  '$600 a week'],
 16: ['sydney+NSW',
  'Research & Insights Analyst',
  'News Corp Australia',
  'location',
  'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....',
  'salary'],
 17: ['Ultimo+NSW',
  'Organisation & Methods Analyst',
  'WEST 1 Australia',
  'location',
  'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...',
  '$55,000 - $65,000 a year'],
 18: ['Ultimo+NSW',
  'Data Analyst, Marketing Strategy & Insights',
  'ANZ Banking Group',
  'location',
  'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....',
  'salary'],
 19: ['Ultimo+NSW',
  'Data Scientist - Analytics',
  'Domain Group',
  'location',
  'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...',
  'salary'],
 20: ['Ultimo+NSW',
  'Data & Reporting Analyst (full-time or part-time opportunity)',
  'AMP Ltd',
  'location',
  "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...",
  'salary'],
 21: ['Ultimo+NSW',
  'Data Analyst - Alexa',
  'Amazon.com',
  'Sydney NSW',
  'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...',
  'salary'],
 22: ['Ultimo+NSW',
  'Data Analyst',
  'Department of Finance, Services & Innovation',
  'Sydney NSW',
  'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...',
  'salary'],
 23: ['Ultimo+NSW',
  'Data Analyst',
  'BT Financial Group',
  'Sydney Central Business District NSW',
  'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...',
  'salary'],
 24: ['Ultimo+NSW',
  'Junior Data Scientist',
  'The Eclair Group',
  'Sydney NSW',
  'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....',
  '$70,000 - $90,000 a year'],
 25: ['Ultimo+NSW',
  'Data Analyst',
  'OpenAgent',
  'Alexandria NSW',
  'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...',
  'salary'],
 26: ['Ultimo+NSW',
  'Data Migration Test analyst',
  'Tata Consultancy Services (TCS)',
  'Sydney NSW',
  'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....',
  '$80,000 - $90,000 a year'],
 27: ['Ultimo+NSW',
  'Data Analyst',
  'Datasii',
  'Sydney NSW',
  'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...',
  '$70,000 - $90,000 a year'],
 28: ['Ultimo+NSW',
  'Data Operations Analyst',
  'Munich Re',
  'Sydney NSW',
  'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...',
  'salary'],
 29: ['Ultimo+NSW',
  'Junior Data Scientist/ Machine Learning Engineer',
  'Intellify',
  'Sydney NSW',
  'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...',
  '$80,000 - $100,000 a year'],
 30: ['Ultimo+NSW',
  'Data Analyst',
  'World Fuel',
  'Sydney NSW',
  'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...',
  'salary'],
 31: ['Ultimo+NSW',
  'Data Analyst',
  'Robert Half Australia',
  'location',
  'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....',
  '$600 a week'],
 32: ['Ultimo+NSW',
  'Research & Insights Analyst',
  'News Corp Australia',
  'location',
  'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....',
  'salary'],
 33: ['sydney+Western+Suburbs',
  'Organisation & Methods Analyst',
  'WEST 1 Australia',
  'location',
  'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...',
  '$55,000 - $65,000 a year'],
 34: ['sydney+Western+Suburbs',
  'Data Analyst, Marketing Strategy & Insights',
  'ANZ Banking Group',
  'location',
  'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....',
  'salary'],
 35: ['sydney+Western+Suburbs',
  'Data Scientist - Analytics',
  'Domain Group',
  'location',
  'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...',
  'salary'],
 36: ['sydney+Western+Suburbs',
  'Data & Reporting Analyst (full-time or part-time opportunity)',
  'AMP Ltd',
  'location',
  "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...",
  'salary'],
 37: ['sydney+Western+Suburbs',
  'Data Analyst - Alexa',
  'Amazon.com',
  'Sydney NSW',
  'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...',
  'salary'],
 38: ['sydney+Western+Suburbs',
  'Data Analyst',
  'Department of Finance, Services & Innovation',
  'Sydney NSW',
  'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...',
  'salary'],
 39: ['sydney+Western+Suburbs',
  'Data Analyst',
  'BT Financial Group',
  'Sydney Central Business District NSW',
  'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...',
  'salary'],
 40: ['sydney+Western+Suburbs',
  'Junior Data Scientist',
  'The Eclair Group',
  'Sydney NSW',
  'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....',
  '$70,000 - $90,000 a year'],
 41: ['sydney+Western+Suburbs',
  'Data Analyst',
  'OpenAgent',
  'Alexandria NSW',
  'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...',
  'salary'],
 42: ['sydney+Western+Suburbs',
  'Data Migration Test analyst',
  'Tata Consultancy Services (TCS)',
  'Sydney NSW',
  'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....',
  '$80,000 - $90,000 a year'],
 43: ['sydney+Western+Suburbs',
  'Data Analyst',
  'Datasii',
  'Sydney NSW',
  'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...',
  '$70,000 - $90,000 a year'],
 44: ['sydney+Western+Suburbs',
  'Data Operations Analyst',
  'Munich Re',
  'Sydney NSW',
  'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...',
  'salary'],
 45: ['sydney+Western+Suburbs',
  'Junior Data Scientist/ Machine Learning Engineer',
  'Intellify',
  'Sydney NSW',
  'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...',
  '$80,000 - $100,000 a year'],
 46: ['sydney+Western+Suburbs',
  'Data Analyst',
  'World Fuel',
  'Sydney NSW',
  'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...',
  'salary'],
 47: ['sydney+Western+Suburbs',
  'Data Analyst',
  'Robert Half Australia',
  'location',
  'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....',
  '$600 a week'],
 48: ['sydney+Western+Suburbs',
  'Research & Insights Analyst',
  'News Corp Australia',
  'location',
  'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....',
  'salary'],
 49: ['Darlinghurst+NSW',
  'Organisation & Methods Analyst',
  'WEST 1 Australia',
  'location',
  'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...',
  '$55,000 - $65,000 a year'],
 50: ['Darlinghurst+NSW',
  'Data Analyst, Marketing Strategy & Insights',
  'ANZ Banking Group',
  'location',
  'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....',
  'salary'],
 51: ['Darlinghurst+NSW',
  'Data Scientist - Analytics',
  'Domain Group',
  'location',
  'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...',
  'salary'],
 52: ['Darlinghurst+NSW',
  'Data & Reporting Analyst (full-time or part-time opportunity)',
  'AMP Ltd',
  'location',
  "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...",
  'salary'],
 53: ['Darlinghurst+NSW',
  'Data Analyst - Alexa',
  'Amazon.com',
  'Sydney NSW',
  'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...',
  'salary'],
 54: ['Darlinghurst+NSW',
  'Data Analyst',
  'Department of Finance, Services & Innovation',
  'Sydney NSW',
  'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...',
  'salary'],
 55: ['Darlinghurst+NSW',
  'Data Analyst',
  'BT Financial Group',
  'Sydney Central Business District NSW',
  'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...',
  'salary'],
 56: ['Darlinghurst+NSW',
  'Junior Data Scientist',
  'The Eclair Group',
  'Sydney NSW',
  'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....',
  '$70,000 - $90,000 a year'],
 57: ['Darlinghurst+NSW',
  'Data Analyst',
  'OpenAgent',
  'Alexandria NSW',
  'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...',
  'salary'],
 58: ['Darlinghurst+NSW',
  'Data Migration Test analyst',
  'Tata Consultancy Services (TCS)',
  'Sydney NSW',
  'Data migration Test Analyst (Automation experience). Data Migration Testing:. Experience in test case design and execution for Data migration activity....',
  '$80,000 - $90,000 a year'],
 59: ['Darlinghurst+NSW',
  'Data Analyst',
  'Datasii',
  'Sydney NSW',
  'Extensive experience as a Data Analyst. At the high level, this Data Analyst will be pivotal in driving decision making by key stakeholders across the business...',
  '$70,000 - $90,000 a year'],
 60: ['Darlinghurst+NSW',
  'Data Operations Analyst',
  'Munich Re',
  'Sydney NSW',
  'Data Operations Analyst (m/f). Support the team and Leader, Data Operations by:Efficient and robust processing of claims and cession data in order to ensure...',
  'salary'],
 61: ['Darlinghurst+NSW',
  'Junior Data Scientist/ Machine Learning Engineer',
  'Intellify',
  'Sydney NSW',
  'We also believe great data science comes from great teams, so invest continuously in upskilling and cross-training our data scientists, with lunch & learn...',
  '$80,000 - $100,000 a year'],
 62: ['Darlinghurst+NSW',
  'Data Analyst',
  'World Fuel',
  'Sydney NSW',
  'Sound data entry and analytical skills. Maintaining customer data within both CRM and Invoice databases. Analyzing customer invoice data to identify erroneous...',
  'salary'],
 63: ['Darlinghurst+NSW',
  'Data Analyst',
  'Robert Half Australia',
  'location',
  'As the Data Analyst you will primarily be responsible for analysis and generating reporting within QlikView....',
  '$600 a week'],
 64: ['Darlinghurst+NSW',
  'Research & Insights Analyst',
  'News Corp Australia',
  'location',
  'Outstanding data extraction and manipulation skills. Interpret and communicate results from data analysis as recommendations to internal customers....',
  'salary'],
 65: ['Barangaroo+NSW',
  'Organisation & Methods Analyst',
  'WEST 1 Australia',
  'location',
  'Data organization, processing and interpretation across all agencies and client data sets. Working with large data sets and tools;...',
  '$55,000 - $65,000 a year'],
 66: ['Barangaroo+NSW',
  'Data Analyst, Marketing Strategy & Insights',
  'ANZ Banking Group',
  'location',
  'Our Data Analysts deeply understand the power of data to generate quality customer insight, manage information, identify trends and make decisions....',
  'salary'],
 67: ['Barangaroo+NSW',
  'Data Scientist - Analytics',
  'Domain Group',
  'location',
  'Prior experience creating beautiful data visualisations. As a Data Scientist in our team, you will leverage your deep experience in statistics, machine learning...',
  'salary'],
 68: ['Barangaroo+NSW',
  'Data & Reporting Analyst (full-time or part-time opportunity)',
  'AMP Ltd',
  'location',
  "We are currently looking for two Data & Reporting Analysts' to join AMP Bank. Assist with Data Governance initiatives including working on the operating model,...",
  'salary'],
 69: ['Barangaroo+NSW',
  'Data Analyst - Alexa',
  'Amazon.com',
  'Sydney NSW',
  'As a Data Analyst you will work closely with the ANZ Alexa Knowledge team, and with other global teams. \uf0a7 Data verification & correction to check data conforms...',
  'salary'],
 70: ['Barangaroo+NSW',
  'Data Analyst',
  'Department of Finance, Services & Innovation',
  'Sydney NSW',
  'Cleanse and prepare multiple sources of data for matching and/or data minining. Working with large data sets from a broad range of sources, taking into...',
  'salary'],
 71: ['Barangaroo+NSW',
  'Data Analyst',
  'BT Financial Group',
  'Sydney Central Business District NSW',
  'In this role you will you will work closely with the Manager to validate all regulatory responses including formal notices for data from APRA and ASIC, and...',
  'salary'],
 72: ['Barangaroo+NSW',
  'Junior Data Scientist',
  'The Eclair Group',
  'Sydney NSW',
  'Industry experience as a Data Analyst or Junior Data Scientist with a track record of manipulating, processing, and extracting value from large datasets....',
  '$70,000 - $90,000 a year'],
 73: ['Barangaroo+NSW',
  'Data Analyst',
  'OpenAgent',
  'Alexandria NSW',
  'Working in the data and business analytics team to answer business questions using data. Review processes that pull data from Adwords and input into our data...',
  'salary'],
 74: ['Barangaroo+NSW',

### Convert to Dataframe

In [24]:
ds_df = pd.DataFrame.from_dict(job_coll)

In [25]:
dsjob_df = ds_df.T

In [26]:
dsjob_df.head(3)

,0,1,2,3,4,5
1,sydney+NSW,Organisation & Methods Analyst,WEST 1 Australia,location,"Data organization, processing and interpretati...","$55,000 - $65,000 a year"
2,sydney+NSW,"Data Analyst, Marketing Strategy & Insights",ANZ Banking Group,location,Our Data Analysts deeply understand the power ...,salary
3,sydney+NSW,Data Scientist - Analytics,Domain Group,location,Prior experience creating beautiful data visua...,salary

In [27]:
dsjob_df.columns = ['city','job_title','company_name','location','summary','salary']

In [28]:
dsjob_df

,city,job_title,company_name,location,summary,salary
1,sydney+NSW,Organisation & Methods Analyst,WEST 1 Australia,location,"Data organization, processing and interpretati...","$55,000 - $65,000 a year"
2,sydney+NSW,"Data Analyst, Marketing Strategy & Insights",ANZ Banking Group,location,Our Data Analysts deeply understand the power ...,salary
3,sydney+NSW,Data Scientist - Analytics,Domain Group,location,Prior experience creating beautiful data visua...,salary
4,sydney+NSW,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,location,We are currently looking for two Data & Report...,salary
5,sydney+NSW,Data Analyst - Alexa,Amazon.com,Sydney NSW,As a Data Analyst you will work closely with t...,salary
6,sydney+NSW,Data Analyst,"Department of Finance, Services & Innovation",Sydney NSW,Cleanse and prepare multiple sources of data f...,salary
7,sydney+NSW,Data Analyst,BT Financial Group,Sydney Central Business District NSW,In this role you will you will work closely wi...,salary
8,sydney+NSW,Junior Data Scientist,The Eclair Group,Sydney NSW,Industry experience as a Data Analyst or Junio...,"$70,000 - $90,000 a year"
9,sydney+NSW,Data Analyst,OpenAgent,Alexandria NSW,Working in the data and business analytics tea...,salary
10,sydney+NSW,Data Migration Test analyst,Tata Consultancy Services (TCS),Sydney NSW,Data migration Test Analyst (Automation experi...,"$80,000 - $90,000 a year"
11,sydney+NSW,Data Analyst,Datasii,Sydney NSW,Extensive experience as a Data Analyst. At the...,"$70,000 - $90,000 a year"
12,sydney+NSW,Data Operations Analyst,Munich Re,Sydney NSW,Data Operations Analyst (m/f). Support the tea...,salary
13,sydney+NSW,Junior Data Scientist/ Machine Learning Engineer,Intellify,Sydney NSW,We also believe great data science comes from ...,"$80,000 - $100,000 a year"
14,sydney+NSW,Data Analyst,World Fuel,Sydney NSW,Sound data entry and analytical skills. Mainta...,salary
15,sydney+NSW,Data Analyst,Robert Half Australia,location,As the Data Analyst you will primarily be resp...,$600 a week
16,sydney+NSW,Research & Insights Analyst,News Corp Australia,location,Outstanding data extraction and manipulation s...,salary
17,Ultimo+NSW,Organisation & Methods Analyst,WEST 1 Australia,location,"Data organization, processing and interpretati...","$55,000 - $65,000 a year"
18,Ultimo+NSW,"Data Analyst, Marketing Strategy & Insights",ANZ Banking Group,location,Our Data Analysts deeply understand the power ...,salary
19,Ultimo+NSW,Data Scientist - Analytics,Domain Group,location,Prior experience creating beautiful data visua...,salary
20,Ultimo+NSW,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,location,We are currently looking for two Data & Report...,salary
21,Ultimo+NSW,Data Analyst - Alexa,Amazon.com,Sydney NSW,As a Data Analyst you will work closely with t...,salary
22,Ultimo+NSW,Data Analyst,"Department of Finance, Services & Innovation",Sydney NSW,Cleanse and prepare multiple sources of data f...,salary
23,Ultimo+NSW,Data Analyst,BT Financial Group,Sydney Central Business District NSW,In this role you will you will work closely wi...,salary
24,Ultimo+NSW,Junior Data Scientist,The Eclair Group,Sydney NSW,Industry experience as a Data Analyst or Junio...,"$70,000 - $90,000 a year"
25,Ultimo+NSW,Data Analyst,OpenAgent,Alexandria NSW,Working in the data and business analytics tea...,salary
26,Ultimo+NSW,Data Migration Test analyst,Tata Consultancy Services (TCS),Sydney NSW,Data migration Test Analyst (Automation experi...,"$80,000 - $90,000 a year"
27,Ultimo+NSW,Data Analyst,Datasii,Sydney NSW,Extensive experience as a Data Analyst. At the...,"$70,000 - $90,000 a year"
28,Ultimo+NSW,Data Operations Analyst,Munich Re,Sydney NSW,Data Operations Analyst (m/f). Support the tea...,salary
29,Ultimo+NSW,Junior Data Scientist/ Machine Learning Engineer,Intellify,Sydney NSW,We also believe great data science comes from ...,"$80,000 - $100,000 a year"
30,Ultimo+NSW,Data Analyst,World Fuel,Sydney NSW,Sound data entry and analytical skills. Mainta...,salary
...,...,...,...,...,...,...
419,New+South+Wales,Data Scientist - Analytics,Domain Group,location,Prior experience creating beautiful data visua...,salary
420,New+South+Wales,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,location,We are currently looking for two Data & Report...,salary
421,New+South+Wales,Data Analyst - Alexa,Amazon.com,Sydney NSW,As a Data Analyst you will work closely with t...,salary
422,New+South+Wales,Data Analyst,"Department of Finance, Services & Innovation",Sydney NSW,Cleanse and prepare multiple sources of data f...,salary
423,New+South+Wales,Data Analyst,BT Financial Group,Sydney Central Business District NSW,In this role you will you will work closely wi...,salary
424,New+South+Wales,Junior Data Scientist,The Eclair Group,Sydney NSW,Industry experience as a Data Analyst or Junio...,"$70,000 - $90,000 a year"
425,New+South+Wales,Data Analyst,OpenAgent,Alexandria NSW,Working in the data and business analytics tea...,salary
426,New+South+Wales,Data Migration Test analyst,Tata Consultancy Services (TCS),Sydney NSW,Data migration Test Analyst (Automation experi...,"$80,000 - $90,000 a year"
427,New+South+Wales,Data Analyst,Datasii,Sydney NSW,Extensive experience as a Data Analyst. At the...,"$70,000 - $90,000 a year"
428,New+South+Wales,Data Operations Analyst,Munich Re,Sydney NSW,Data Operations Analyst (m/f). Support the tea...,salary
429,New+South+Wales,Junior Data Scientist/ Machine Learning Engineer,Intellify,Sydney NSW,We also believe great data science comes from ...,"$80,000 - $100,000 a year"
430,New+South+Wales,Data Analyst,World Fuel,Sydney NSW,Sound data entry and analytical skills. Mainta...,salary
431,New+South+Wales,Data Analyst,Robert Half Australia,location,As the Data Analyst you will primarily be resp...,$600 a week
432,New+South+Wales,Research & Insights Analyst,News Corp Australia,location,Outstanding data extraction and manipulation s...,salary
433,Melbourne+VIC,Organisation & Methods Analyst,WEST 1 Australia,location,"Data organization, processing and interpretati...","$55,000 - $65,000 a year"
434,Melbourne+VIC,"Data Analyst, Marketing Strategy & Insights",ANZ Banking Group,location,Our Data Analysts deeply understand the power ...,salary
435,Melbourne+VIC,Data Scientist - Analytics,Domain Group,location,Prior experience creating beautiful data visua...,salary
436,Melbourne+VIC,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,location,We are currently looking for two Data & Report...,salary
437,Melbourne+VIC,Data Analyst - Alexa,Amazon.com,Sydney NSW,As a Data Analyst you will work closely with t...,salary
438,Melbourne+VIC,Data Analyst,"Department of Finance, Services & Innovation",Sydney NSW,Cleanse and prepare multiple sources of data f...,salary
439,Melbourne+VIC,Data Analyst,BT Financial Group,Sydney Central Business District NSW,In this role you will you will work closely wi...,salary
440,Melbourne+VIC,Junior Data Scientist,The Eclair Group,Sydney NSW,Industry experience as a Data Analyst or Junio...,"$70,000 - $90,000 a year"
441,Melbourne+VIC,Data Analyst,OpenAgent,Alexandria NSW,Working in the data and business analytics tea...,salary
442,Melbourne+VIC,Data Migration Test analyst,Tata Consultancy Services (TCS),Sydney NSW,Data migration Test Analyst (Automation experi...,"$80,000 - $90,000 a year"
443,Melbourne+VIC,Data Analyst,Datasii,Sydney NSW,Extensive experience as a Data Analyst. At the...,"$70,000 - $90,000 a year"
444,Melbourne+VIC,Data Operations Analyst,Munich Re,Sydney NSW,Data Operations Analyst (m/f). Support the tea...,salary
445,Melbourne+VIC,Junior Data Scientist/ Machine Learning Engineer,Intellify,Sydney NSW,We also believe great data science comes from ...,"$80,000 - $100,000 a year"
446,Melbourne+VIC,Data Analyst,World Fuel,Sydney NSW,Sound data entry and analytical skills. Mainta...,salary
447,Melbourne+VIC,Data Analyst,Robert Half Australia,location,As the Data Analyst you will primarily be resp...,$600 a week
448,Melbourne+VIC,Research & Insights Analyst,News Corp Australia,location,Outstanding data extraction and manipulation s...,salary

### City and Location Column basically the same, Drop Location Column as City are more complete

In [29]:
dsjob_df = dsjob_df.drop(columns={'location'})

In [30]:
dsjob_df.head()

,city,job_title,company_name,summary,salary
1,sydney+NSW,Organisation & Methods Analyst,WEST 1 Australia,"Data organization, processing and interpretati...","$55,000 - $65,000 a year"
2,sydney+NSW,"Data Analyst, Marketing Strategy & Insights",ANZ Banking Group,Our Data Analysts deeply understand the power ...,salary
3,sydney+NSW,Data Scientist - Analytics,Domain Group,Prior experience creating beautiful data visua...,salary
4,sydney+NSW,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,We are currently looking for two Data & Report...,salary
5,sydney+NSW,Data Analyst - Alexa,Amazon.com,As a Data Analyst you will work closely with t...,salary

In [31]:
dsjob_df.city.unique()

array(['sydney+NSW', 'Ultimo+NSW', 'sydney+Western+Suburbs',
       'Darlinghurst+NSW', 'Barangaroo+NSW', 'Mascot+NSW',
       'Parramatta+NSW', 'Surry+Hills+NSW', 'Macquarie+Park+NSW',
       'sydney+Inner+Suburbs+NSW', 'Hills+District+NSW',
       'sydney+Central+Business+District+NSW', 'New+South+Wales',
       'Melbourne+VIC'], dtype=object)

In [32]:
c = dsjob_df.replace('sydney+W.+','Sydney', regex=True)

In [33]:
c.to_csv('./data/danalyst3.csv')

In [127]:
d = pd.read_csv('./Data/danalyst3.csv')

In [128]:
e = d.replace('Ulti.+','Ultimo', regex=True)

In [129]:
e = e.replace('syd.+','sydney', regex=True)

In [130]:
e = e.replace('Baran.+','Barangaroo', regex=True)

In [131]:
e = e.replace('Masc.+','Mascot', regex=True)

In [132]:
e = e.replace('Parr.+','Parramatta', regex=True)

In [133]:
e = e.replace('Surr.+','Surry Hills', regex=True)

In [134]:
e = e.replace('Macq.+','Macquarie Park', regex=True)

In [135]:
e = e.replace('Hill.+','Hills District', regex=True)

In [136]:
e = e.replace('New.+','Sydney', regex=True)

In [137]:
e = e.replace('Melb.+','Melbourne', regex=True)

In [138]:
e = e.replace('Surr.+','Surry Hills', regex=True)

In [139]:
e.city.unique()

array(['sydney', 'Ultimo', 'Darlinghurst+NSW', 'Barangaroo', 'Mascot',
       'Parramatta', 'Surry Hills', 'Macquarie Park', 'Hills District',
       'Sydney', 'Melbourne'], dtype=object)

In [140]:
e.job_title.unique()

array(['Organisation & Methods Analyst',
       'Data Analyst, Marketing Strategy & Insights',
       'Data Scientist - Analytics',
       'Data & Reporting Analyst (full-time or part-time opportunity)',
       'Data Analyst - Alexa', 'Data Analyst', 'Junior Data Scientist',
       'Data Migration Test analyst', 'Data Operations Analyst',
       'Junior Data Scientist/ Machine Learning Engineer',
       'Research & Insights Analyst'], dtype=object)

In [141]:
e =e.replace('Organ.+', 'Analyst', regex=True)

In [142]:
e =e.replace('Market.+', 'Analyst', regex=True)

In [143]:
e =e.replace('Data Sci.+', 'Data Scientist', regex=True)

In [144]:
e =e.replace('Data Mig.+', 'Data Analyst', regex=True)

In [145]:
e =e.replace('Data Op.+', 'Data Analyst', regex=True)

In [146]:
e =e.replace('/.+', '', regex=True)

In [147]:
e =e.replace('Rese.+', 'Analyst', regex=True)

In [148]:
e =e.replace('Data Analy.+', 'Data Analyst', regex=True)

In [149]:
e.job_title.unique()

array(['Analyst', 'Data Analyst', 'Data Scientist',
       'Data & Reporting Analyst (full-time or part-time opportunity)',
       'Junior Data Scientist'], dtype=object)

In [150]:
e.columns

Index(['Unnamed: 0', 'city', 'job_title', 'company_name', 'summary', 'salary'], dtype='object')

In [151]:
e = e.drop(columns='Unnamed: 0')

In [156]:
e.to_csv('./data/danayst5.csv')

In [185]:
h_df = pd.read_csv('./data/danayst6.csv')

In [187]:
h_df.head()

,Column,city,job_title,company_name,summary,salary_lower,salary_upper
0,0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...","$55,000","$65,000"
1,1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,salary,NaN
2,2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,salary,NaN
3,3,sydney,Data & Reporting Analyst (full-time or part-ti...,AMP Ltd,We are currently looking for two Data & Report...,salary,NaN
4,4,sydney,Data Analyst,Amazon.com,As a Data Analyst,salary,NaN

In [188]:
h_df.salary_lower.replace('salary', 0, inplace=True)

In [189]:
h_df.salary_lower.replace('[$,]', '', regex=True, inplace=True)

In [198]:
h_df.salary_upper.replace('[A-z$,]', '', regex=True, inplace=True)

In [202]:
h_df = h_df.fillna(0)

In [207]:
h_df.to_csv('./data/danalyst7.csv')

In [212]:
h_df = pd.read_csv('./data/danalyst8.csv')

In [215]:
h_df[['salary_lower', 'salary_upper']] = h_df[['salary_lower', 'salary_upper']].astype('float64')

In [216]:
h_df =h_df.replace('Data &.+', 'Data Analyst', regex=True)

In [217]:
h_df.head()

,city,job_title,company_name,summary,salary_lower,salary_upper
0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0
1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,0.0,0.0
2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,0.0,0.0
3,sydney,Data Analyst,AMP Ltd,We are currently looking for two Data Analyst,0.0,0.0
4,sydney,Data Analyst,Amazon.com,As a Data Analyst,0.0,0.0

In [210]:
h_df.dtypes

Column            int64
Column2           int64
city             object
job_title        object
company_name     object
summary          object
salary_lower    float64
salary_upper    float64
dtype: object

Replace 0 back to NAN as it cannot calculate the Median.

In [218]:
j_df = h_df.replace(0, np.nan)

In [219]:
j_df.head()

,city,job_title,company_name,summary,salary_lower,salary_upper
0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0
1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,NaN,NaN
2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,NaN,NaN
3,sydney,Data Analyst,AMP Ltd,We are currently looking for two Data Analyst,NaN,NaN
4,sydney,Data Analyst,Amazon.com,As a Data Analyst,NaN,NaN

In [221]:
j_df['median_salary_lower'] = j_df.groupby('job_title')['salary_lower'].transform('median')

In [222]:
j_df['median_salary_upper'] = j_df.groupby('job_title')['salary_upper'].transform('median')

In [223]:
j_df.head()

,city,job_title,company_name,summary,salary_lower,salary_upper,median_salary_lower,median_salary_upper
0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0,55000.0,65000.0
1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,NaN,NaN,70000.0,90000.0
2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,NaN,NaN,NaN,NaN
3,sydney,Data Analyst,AMP Ltd,We are currently looking for two Data Analyst,NaN,NaN,70000.0,90000.0
4,sydney,Data Analyst,Amazon.com,As a Data Analyst,NaN,NaN,70000.0,90000.0

In [224]:
j_df.salary_lower.fillna(j_df.median_salary_lower, inplace=True)

In [225]:
j_df.salary_upper.fillna(j_df.median_salary_upper, inplace=True)

In [226]:
j_df.head()

,city,job_title,company_name,summary,salary_lower,salary_upper,median_salary_lower,median_salary_upper
0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0,55000.0,65000.0
1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,70000.0,90000.0,70000.0,90000.0
2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,NaN,NaN,NaN,NaN
3,sydney,Data Analyst,AMP Ltd,We are currently looking for two Data Analyst,70000.0,90000.0,70000.0,90000.0
4,sydney,Data Analyst,Amazon.com,As a Data Analyst,70000.0,90000.0,70000.0,90000.0

In [227]:
j_df.drop(['median_salary_lower','median_salary_upper'], axis=1, inplace=True)

In [228]:
j_df.head()

,city,job_title,company_name,summary,salary_lower,salary_upper
0,sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0
1,sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,70000.0,90000.0
2,sydney,Data Scientist,Domain Group,Prior experience creating beautiful data visua...,NaN,NaN
3,sydney,Data Analyst,AMP Ltd,We are currently looking for two Data Analyst,70000.0,90000.0
4,sydney,Data Analyst,Amazon.com,As a Data Analyst,70000.0,90000.0

In [229]:
j_df.to_csv('./data/jobs4.csv')

In [235]:
j_df['mean_salary'] = (j_df.salary_lower + j_df.salary_upper) / 2

In [236]:
j_df = j_df.replace('syd.+','Sydney', regex=True)

In [237]:
j_df.head(2)

,city,job_title,company_name,summary,salary_lower,salary_upper,mean_salary
0,Sydney,Analyst,WEST 1 Australia,"Data organization, processing and interpretati...",55000.0,65000.0,60000.0
1,Sydney,Data Analyst,ANZ Banking Group,Our Data Analyst,70000.0,90000.0,80000.0

In [240]:
j_df.to_csv('./data/datafinal2.csv')